export const palette1: string;
export const palette2: string;
export const palette3: string;
export const palette4: string;
export const palette5: string;
export const gxs: string;
export const gsm: string;
export const gm: string;
export const button: string;
